### ISSUE TITLE
using gridstack template on MyBinder hosted Voila dashboard

### ISSUE THREAD

**Issue by cornhundred** [voila-dashboards/voila-gridstack#10]
Can we use the gridtack template on MyBinder hosted voila dashboards? I would like to do so for this repo: 

https://github.com/ismms-himc/gaussian-density

MyBinder link to Voila Dashboard from this repo: 
https://mybinder.org/v2/gh/ismms-himc/gaussian-density/master?urlpath=voila%2Frender%2Findex.ipynb

I added grid-stack to the [requirements.txt](https://github.com/ismms-himc/gaussian-density/blob/master/requirements.txt#L4), but I'm not sure how/if I can get MyBinder to render using this template.

I raised a similar issue about positioning dashboard components (e.g. widgets) side-by-side here: https://github.com/QuantStack/voila/issues/336

**Comment by jtpio** [comment]
@cornhundred have you tried using a `jupyter_config.json` file, like for the voila-demo repo? https://github.com/maartenbreddels/voila-demo/blob/4b84414309bc53350a63b704add34163eb5c489d/jupyter_config.json

The content would look like this:

```json
{
    "VoilaConfiguration": {
        "enable_nbextensions": true,
        "template": "gridstack"
    }
}
```

**Comment by jtpio** [comment]
Closing as answered.

Also feel free to check out the [voila-demo](https://github.com/maartenbreddels/voila-demo) repo which does exactly that!

**Comment by cornhundred** [comment]
Thanks!
