### ISSUE TITLE
Styling gridstack template

### ISSUE THREAD

**Issue by LuisFRoch** [voila-dashboards/voila-gridstack#11]
Hi, so i've tried creating a template (following customize.rst & https://voila.readthedocs.io/en/latest/customize.html) and making small adjustments to the default style (e.g. color, header) but the best result is the default light-grey color with new title and no widget rendering. If i adjust the original voila.tpl then i get the widgets with title but no color =S 
How can i make adjustments to the template?
Thanks!

**Comment by SylvainCorlay** [comment]
Hey @LuisFRoch sorry for not responding earlier - this got lost in my backlog.

We are putting some effort into voila-gridstack into the next couple of weeks and hopefully it will become more customizable.

**Comment by LuisFRoch** [comment]
Martin also gave me the heads-up, and thanks for the update @SylvainCorlay.

**Comment by SylvainCorlay** [comment]
OK, closing the issue !
