### ISSUE TITLE
Add pin button in widget toolbar

### ISSUE THREAD

**Issue by fcollonval** [voila-dashboards/voila-gridstack#110]
Having a pin button in grid widget toolbar to freeze their position and size would be a great addition.

**Comment by hbcarlos** [comment]
There is a new option in gridstack v4.
> `locked` - means another widget wouldn't be able to move it during dragging or resizing. The widget can still be dragged or resized by the user. You need to add noResize and noMove attributes to completely lock the widget.

I think this cloud be the best approach.

**Comment by hbcarlos** [comment]
Addressed by #116
