### ISSUE TITLE
AttributeError: 'VoilaHandler' object has no attribute 'exporter'

### ISSUE THREAD

**Issue by t8ch** [voila-dashboards/voila-gridstack#12]
Using voila with the default template works fine but using gridstack prompts:
``` 
File "/home/user/miniconda3/lib/python3.7/site-packages/voila/handler.py", line 125, in _jinja_notebook_execute
File "/home/user/miniconda3/lib/python3.7/site-packages/voila/handler.py", line 125, in <lambda>
result.cells = list(filter(lambda cell: filter_empty_code_cells(cell, self.exporter), result.cells))
AttributeError: 'VoilaHandler' object has no attribute 'exporter' 
ERROR:tornado.general:Cannot send error response after headers written
```
this is the versions I am using (I have tried different orders of reinstalling libraries via conda):
`voila                     0.1.11                     py_0    conda-forge
`
`voila-gridstack          0.0.6                      py_0    conda-forge
`

does anyone have an idea what the problem might be?

**Comment by jtpio** [comment]
Thanks @t8ch for the report.

This seems to be related to the recent switch to the progressive rendering for the default template in voila.
At the moment the `gridstack` does not implement progressive rendering and uses a different code path: https://github.com/voila-dashboards/voila/blob/80c1b499ee2c128a85587868bd60229a53c3b563/voila/handler.py#L123-L130

**Comment by t8ch** [comment]
Thanks a lot!
So, as I take it, the current version of `voila` is incompatible with the current version of `gridstack`? Just want to make sure I am not missing an obvious workaround (except downgrading).

**Comment by jtpio** [comment]
If you want you could stick to 0.1.10 for now until we fix it and make a new release (https://github.com/voila-dashboards/voila/pull/389). The main change between 0.1.10 and 0.1.11 is the progressive rendering.

**Comment by jtpio** [comment]
@t8ch a new version of voila (0.1.12) has been published, and should be available on conda-forge really soon.

Let us know if it solves the issue!

**Comment by t8ch** [comment]
it does solve the problem! thanks.

(as of now, 0.1.12 is available through pip but not conda)

**Comment by jtpio** [comment]
Good to hear, closing as fixed!
