### ISSUE TITLE
How to make fixed layout where one is not able to drag elements around?

### ISSUE THREAD

**Issue by jjaakko** [voila-dashboards/voila-gridstack#128]
This example from https://gridstackjs.com/demo/static.html# features a grid where elements cannot be moved around, apparently by utilizing a property of `"noMove": true`. After creating a layout with gridstack (by clicking the gridstack button in a jupyter lab) and moving cells to the appropriate positions, how can I lock the elements so that when the app is displayed by voila, the elements cannot be moved?

Using the following versions:  
voila = 0.2.9
voila-gridstack = 0.2.0

**Comment by hbcarlos** [comment]
Hi, when opening the notebook with Voila, by default, the layout is fixed. You can not move elements once the notebook is launched with voila.

If you want to edit the layout in Voila, you have to add this option when launching the app.
`--VoilaConfiguration.resources='{"gridstack": {"show_handles": True}}'`

**Comment by jjaakko** [comment]
But this is the exact issue for me. When I am launching the notebook with Voila and gridstack I am able to drag the elements around, even when no handles are shown.

I also tried to launch voila with voila `--template=gridstack --VoilaConfiguration.resources='{"gridstack": {"show_handles": False}}` but the elements are still draggable.

**Comment by hbcarlos** [comment]
Yeah, I tried locally, and it's a bug. Thanks for reporting this.
Also, in the readme, there is an old screencast we need to change.

**Comment by hbcarlos** [comment]
Hi @jjaakko, I merged a PR for this issue.
Give it a try installing from the master branch, and if the issue remains, feel free to reopen!
