### ISSUE TITLE
Widget not displayed in gridstack

### ISSUE THREAD

**Issue by IvanPalm** [voila-dashboards/voila-gridstack#132]
I am attempting to generate a GIS dashboard so I started from its core element: an interactive map. Widgets, charts and more will follow.  

The map renders flawless in JupyterLab and Voila, but it doesn't when I try to use the gridstack template. This applies to the JupyterLab extension (shown below) and to the command line tool too.  

Here the map open in Voila extension
![Screenshot from 2021-05-10 10-15-22](https://user-images.githubusercontent.com/46936982/117638296-f6d5be80-b182-11eb-842f-3e505acae3cd.png)

Here in Voila gridstack extension
![Screenshot from 2021-05-10 10-16-17](https://user-images.githubusercontent.com/46936982/117638482-297fb700-b183-11eb-9a22-033082c0b155.png)

As for the command line tool, the command `voila notebooks/smap_app.ipynb` returns warning messages such as `WARNING:tornado.general:403 GET /voila/files/voila/jupyter-leaflet.js (127.0.0.1): File not whitelisted` while the map is displayed normally in the browser.  
Conversely, the command `voila notebooks/smap_app.ipynb --template=gridstack` does not return any warning, but neither the map nor the title are displayed in the browser.

I am working in Ubuntu 20.04, here the specs of the environment:
```
conda 4.10.1
Python 3.9.2
voila 0.2.9
voila-gridstack 0.2.0
jupyter core     : 4.7.1
jupyter-notebook : 6.3.0
qtconsole        : not installed
ipython          : 7.22.0
ipykernel        : 5.5.3
jupyter client   : 6.1.12
jupyter lab      : 3.0.14
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.3
traitlets        : 5.0.5
```
And here the output of `jupyter labextension list`:
```
JupyterLab v3.0.14
/home/ivan/miniconda3/envs/pygis/share/jupyter/labextensions
        jupyter-threejs v2.3.0 enabled OK (python, pythreejs)
        jupyterlab-datawidgets v7.0.0 enabled OK
        jupyter-matplotlib v0.9.0 enabled OK
        jupyter-webrtc v0.6.0 enabled OK
        jupyter-leaflet v0.13.5 enabled OK
        ipytree v0.2.1 enabled OK
        ipyvolume v0.6.0-alpha.8 enabled OK
        bqplot v0.5.27 enabled OK (python, bqplot)
        @voila-dashboards/jupyterlab-gridstack v0.2.0 enabled OK (python, voila-gridstack)
        @voila-dashboards/jupyterlab-preview v2.0.2 enabled OK (python, voila)
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: /home/ivan/miniconda3/envs/pygis/share/jupyter/lab
        @jupyterlab/geojson-extension v3.1.2 enabled OK
        ipyevents v1.8.2 enabled OK
```

Could anyone help me configuring gridstack to use as JupyterLab extension and/or command line tool?

**Comment by hbcarlos** [comment]
Hi @IvanPalm, thanks for opening this issue.

When you drag and drop a cell from the notebook to the editor, does the cell show an error?
And if it does, what's the error?
