### ISSUE TITLE
Error displaying widgets in Gridstack editor in Jupyter Lab

### ISSUE THREAD

**Issue by gdomst** [voila-dashboards/voila-gridstack#138]
Hi, I can't see the widgets in the GridStack editor

![gridstack](https://user-images.githubusercontent.com/86971690/124489348-3c7bc580-dd87-11eb-840c-218cf5befe63.png)
When I open GridStack in a new tab it works fine. I can see them.

The extensions installed
```
$ jupyter labextension list
JupyterLab v3.0.6
/home/gianfranco/.local/share/jupyter/labextensions
        jupyter-vue v1.5.0 enabled OK
        jupyter-matplotlib v0.8.3 enabled OK
        jupyter-vuetify v1.7.0 enabled OK
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)
        @voila-dashboards/jupyterlab-preview v2.0.2 enabled OK (python, voila)
        @voila-dashboards/jupyterlab-gridstack v0.2.0 enabled OK (python, voila-gridstack)

Other labextensions (built into JupyterLab)
   app dir: /home/gianfranco/.local/share/jupyter/lab
        bqplot v0.5.30 enabled OK
        install v0.13.0 enabled OK
```

Voila and voila-gridstack  versions 
```
$ pip3 list | egrep 'voila'
voila               0.2.10       
voila-gridstack     0.2.0        
```

**Comment by hbcarlos** [comment]
Hi @gdomst, thanks for opening this issue.

You are right, we have some troubles with this issue. When opening a notebook and then opening the voila-gridstack editor without executing the cells first, widgets don't show up on the editor.

Could you try to re-execute the notebook?

**Comment by gdomst** [comment]
Hi @hbcarlos thank you for replying. I re-executed the notebook as you mentioned. I ran the cells first (widgets works fine in the notebook) and then I lunched the GridStack editor. The latter killed the notebook widgets. The notebook says "error" and the GridStack editor says "loading".

Here is a screenshot:
![gridstack2](https://user-images.githubusercontent.com/86971690/124495606-b2cff600-dd8e-11eb-8b7c-f60da6eff99b.png)

**Comment by hbcarlos** [comment]
Ooh, I'm sorry I was wrong. We need to have the notebook and the editor open and then re-execute.
Could you try that and let me know if it works?

This is an issue that we have due to Ipywidgets.

**Comment by gdomst** [comment]
Same result as the first screenshot I posted. Outputs other than Ipywidgets works fine :(

**Comment by hbcarlos** [comment]
Hi @gdomst, sorry for the late response.

What Ipywidgets version are you using?
