### ISSUE TITLE
GridStack interferes with ability to drag elements in perspective widget

### ISSUE THREAD

**Issue by dhirschfeld** [voila-dashboards/voila-gridstack#139]
The [`perspective`](https://github.com/finos/perspective) widget depends on the ability to drag elements about to e.g. filter the grid.

It appears `voila-gridstack` hijacks the drag control to move the `perspective` widget itself. When rendered with `voila` where the widgets are fixed the `perspective` drag-and-drop works fine.

Seems related to https://github.com/voila-dashboards/voila-gridstack/issues/128

**Comment by hbcarlos** [comment]
Hi @dhirschfeld, I'm sorry for the late response.

Is this happening in Voila when using the gridstack template or in the Voila Gridstack Editor in JupyterLab?
Can you send a notebook example using perspective?

**Comment by dhirschfeld** [comment]
> Is this happening in Voila when using the gridstack template or in the Voila Gridstack Editor in JupyterLab?

When using the gridstack template.

> Can you send a notebook example using perspective?

I'll knock one up for you in the morning...

**Comment by hbcarlos** [comment]
Nice! Thank you soo much.

**Comment by hbcarlos** [comment]
Hi @dhirschfeld. I just merged a fix for #128. Could you give it a try installing from the master branch, and let me know if the issue remains?

**Comment by jpswinski** [comment]
I am still seeing this issue.  I installed from main 
```
voila-gridstack           0.3.0b1
```
I am rendering an ipyleaflet map and the drag controls are inhibited by the ability to move the entire grid cell.

I also tried `--VoilaConfiguration.resources='{"gridstack": {"show_handles": False}}` with no luck.
