### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by jtpio** [voila-dashboards/voila-gridstack#146]
Checklist for cutting the next release:

- [x] Update to Jupyter Packaging 0.10: https://github.com/voila-dashboards/voila-gridstack/pull/145
- [x] Adopt the Jupyter Releaser: https://github.com/voila-dashboards/voila-gridstack/issues/147
- [x] Add a script to bump the version of the Python package and JupyterLab extension
- [x] Rename master to main and update GitHub workflows: https://github.com/voila-dashboards/voila-gridstack/pull/152
- [x] Release `0.3.0`

**Comment by jtpio** [comment]
With https://github.com/voila-dashboards/voila-gridstack/pull/148 we adopt the Jupyter Releaser for making releases.

We can start with a `0.3.0a0` first. To make that release:

### Sync the `jupyter_releaser` fork

To make sure our fork is up-to-date:

![image](https://user-images.githubusercontent.com/591645/139919648-47e77209-7157-4b69-bfa4-ca57508e9264.png)

### Draft Changelog

![image](https://user-images.githubusercontent.com/591645/139919826-eb750b46-d0f5-4fec-9457-0bd5de7077d5.png)

### Full Release

After merging the changelog PR, we run the full release workflow:

![image](https://user-images.githubusercontent.com/591645/139919914-404d616b-e4aa-448e-bdf1-862aee7f5003.png)

**Comment by jtpio** [comment]
The default branch has been renamed to `main`.

**Comment by hbcarlos** [comment]
The release is done and it works perfectly using `pip install voila-gridstack==0.3.0a0`.
Waiting for the conda-forge to open the PR.

**Comment by jtpio** [comment]
>  Waiting for the conda-forge to open the PR.

We can also skip conda-forge for prereleases for now it's fine.

**Comment by jtpio** [comment]
@hbcarlos do you know if there is any remaining things to be done before releasing `0.3.0`?

@Zsailer is excited about the upcoming `0.3.0` final release, so maybe this could happen very soon :)

**Comment by Zsailer** [comment]
Yes! I tried this out yesterday. It's awesome! I'd like to start advertising this a bit more. 

I see that you incorporated some UX from the Jupyter Cal Poly Intern team, too. Maybe we can give that team some shoutouts too!

**Comment by hbcarlos** [comment]
Hey @jtpio, I don't think soo. I can make the release today.

**Comment by hbcarlos** [comment]
Hi @Zsailer! Thank you for the kind words. I'm glad you liked it.
We should definitely mention the fantastic work from the Jupyter Cal Poly team. Their extension inspired some of the UX design.

**Comment by hbcarlos** [comment]
Voila-gridstack v0.3.0 is out https://github.com/voila-dashboards/voila-gridstack/releases/tag/v0.3.0

**Comment by jtpio** [comment]
Nice, thanks!

**Comment by Zsailer** [comment]
Y'all are awesome. Thank you!
