### ISSUE TITLE
gridstack templates don't work when installed with setup.py

### ISSUE THREAD

**Issue by btel** [voila-dashboards/voila-gridstack#15]
Installing voila-gridstack from the working directory with:

```
python setup.py install
```

shows no error, but running voila with gridstack template:

```
voila Untitled.ipynb --template=gridstack
```

gives this error:

```
ValueError: No template sub-directory with name 'gridstack' found in the following paths:
	/home/bartosz/.local/share/jupyter/voila/templates
	/home/bartosz/.pyenv/versions/quantstack-voila-gridstack/share/jupyter/voila/templates
	/usr/local/share/jupyter/voila/templates
	/usr/share/jupyter/voila/templates
```

I don't find gridstack templates in `/home/bartosz/.pyenv/versions/quantstack-voila-gridstack/share/jupyter/voila/templates` directory (my virualenv).

Installing with `pip install voila-gridstack` works fine and creates the directory `/home/bartosz/.pyenv/versions/quantstack-voila-gridstack/share/jupyter/voila/templates/gridstack`.

This problem is probably related to the fact that `setup.py` installs `voila-gridstack` templates in the egg file and won't copy them to virtualenv directories, i.e. running `python setup.py install -v` shows this message:

"Copying voila_gridstack-0.0.6-py3.7.egg to /home/bartosz/.pyenv/versions/3.7.4/envs/quantstack-voila-gridstack/lib/python3.7/site-packages"

**Comment by btel** [comment]
I tried also:

```
pip install .
```

and 

```
pip install -e .
```

with same results.

**Comment by SylvainCorlay** [comment]
@btel I always use pip and never saw any issue. Is this due to the use of a virtual environment?

**Comment by btel** [comment]
Indeed, it works with `pip install .` (without `-e`). I just needed to uninstall all voila-gridstack artifacts (`easy-install.pth`, `.egg-link`, etc.). Thanks @SylvainCorlay !

**Comment by SylvainCorlay** [comment]
Thanks! Closing the issue.

We should work on streamlining development workflows for Voilà templates at some point.
