### ISSUE TITLE
Can't drag cell directly to lower parts of scrolled down grid.

### ISSUE THREAD

**Issue by bdklahn** [voila-dashboards/voila-gridstack#150]
## Description

If a grid becomes long enough to get the scroll bar, the cell gets placed higher up than where it is dragged to.
(and moves and messes things up, which apparently can't be undone unless closing without saving the notebook, then re-opening)

## Reproduce

1. Insert enough markdown elements by dragging down to extend grid.
2. Scroll down.
3. Try and drag to place an element lower on the grid.

It looks like the grid window and the scrolled view are out of sync, because I can see a "phantom" cell outline above where I am dragging, which seems to be too high by about the same amount as the grid is scrolled down.

## Expected behavior

Cell should land where it is placed in the scrolled view.

## Context
- voila version '0.2.16'
- Operating System and version: OpenSUSE Tumbleweed
- Browser and version: Firefox 93.0 (64 bit)

### If using JupyterLab
- JupyterLab version: 3.2.0

**Comment by bdklahn** [comment]
@hbcarlos 
Thanks so much for you time on this!

You said the screen cast was so you can "debug it fastly". But I guess I wondered how it can be reliably debugged without an actual reproduction, based on my simple description, (vs. seeing a video of the behavior being produced).

Anyway, I totally agree that added information might make a nice reference documentation, for people to quickly assess if a future Issue might be a duplicate, or something. -and a (moving) picture can be "worth a thousand words".

And I realize my relatively use environment might not be the most fruitful for devs to spend time on.
But I can provide a Singularity def file, if anyone ever wants to use it to make a reproducible environment for OpenSUSE Tumbleweed.

I see that, compared to many repos, there are not many Issues contributed. I wonder if a non-programmer end-user coming in might be intimidated by the extensive boilerplate template Issue text. They might only have time to come in and not say much more than a quick "Hey there's this issue you might want to note.", just to get **something** documented.
I understand that is a great way to prompt people to add necessary information up front, which people will likely have to spend time communicating anyway, in the course of Issue resolution. But I wonder if a non-programmer end-user might come in, see all that "required" input, and think "Forget it. I'll just move on.".

And it is then a little deflating when you spend a little time on a "reproduce" section, and a dev doesn't seem to have even tried it, without asking for even more (arguably unnecessary) effort.

But on a lighter note, this and Jupyter are very useful to a lot of folks. So thank you for your time in working on this! And I suppose I could be a little more accommodating/forgiving, given that this is all free software.

Thanks again!

**Comment by hbcarlos** [comment]
@bdklahn The issue is already solved on #151. I'll merge and release it as soon as possible.

Regarding the issue template, I agree with you. It asks for too much information that we sometimes don't need, and it can make some users avoid reporting issues.

Thanks again for reporting the issue. It is an important one that we missed.

**Comment by bdklahn** [comment]
Awesome that this is solved! Thanks!

Maybe you could mostly leave the template . . . as the requested information is often helpful.
But maybe have sections headed (or commented as) something like . . .
## Very Useful Information
. . .

## Often Useful Information
. . .

## Sometimes Useful Information
. . .

Idk . . . just thoughts.

**Comment by hbcarlos** [comment]
@bdklahn We released an alpha version with the fixes for this issue. You can install it using `pip install voila-gridstack==0.3.0a0`.
