### ISSUE TITLE
Can't set show_handles=True via config

### ISSUE THREAD

**Issue by pmarcellino** [voila-dashboards/voila-gridstack#204]
The problem I'm having is that I am using voila-gridstack as a jupyterhub server extension, so I can't pass the arguments on the run command as sugested in the readme. I tried to set it via config, but I think this line here makes it so that I can't set show_handles via config?

From `voila_gridstack/server_extension.py`
![image](https://user-images.githubusercontent.com/46568443/217091857-9a84dd23-1a49-4cdf-9d5c-16238d9c1cca.png)

**Comment by jpjon** [comment]
Try replacing that with `"{'gridstack': {'show_handles': True, 'extension': True}}" `

I had a lot of issues with this, even when copy and pasting from this repo's READ.me's documentation. How I solved it was by seeing an example of how voila accepted parameters for `VoilaConfiguration.resources` by running `voila --help-all`, which differs from the implementation from this repository's READ.me. This led me to change the quotation format above.

**Comment by hbcarlos** [comment]
Thank you for the explanation @jpjon!
