### ISSUE TITLE
nothing provides requested voila-gridstack 0.3.1

### ISSUE THREAD

**Issue by pmarcellino** [voila-dashboards/voila-gridstack#205]
It seems like version 0.3.1 isn't fully released, but is marked as latest, when I run `mamba install voila-gridstack==0.3.1` I get the following error
![image](https://user-images.githubusercontent.com/46568443/217658398-eb9a5e37-83d2-4d73-a2b5-f8e3ac4753fe.png)

**Comment by hbcarlos** [comment]
Hi @pmarcellino! Thanks for opening the issue.
It should be fixed in a few hours. There was an error with the recipe. I fixed it in https://github.com/conda-forge/voila-gridstack-feedstock/pull/19

Feel free to reopen the issue if it's fixed by tomorrow.
