### ISSUE TITLE
Conda recipe for 0.3.1 does not accepts voila-0.4.0

### ISSUE THREAD

**Issue by juanfem** [voila-dashboards/voila-gridstack#207]
I am trying to install voila-0.4.0 together with voila-gridstack-0.3.1 ([which I understand it's supported](https://github.com/voila-dashboards/voila-gridstack/pull/193)), but it seems that the conda recipe is out of date (see https://github.com/conda-forge/voila-gridstack-feedstock/blob/main/recipe/meta.yaml#L28).

```
$ mamba install -c conda-forge voila-gridstack==0.3.1 voila==0.4.0
[...]
Could not solve for environment specs
The following packages are incompatible
├─ voila-gridstack 0.3.1  is installable and it requires
│  └─ voila >=0.2.0,<0.4 , which can be installed;
└─ voila 0.4.0  is uninstallable because it conflicts with any installable versions previously reported.
```

**Comment by hbcarlos** [comment]
Hi @juanfem. Thanks for the heads-up.

I just modified the recipe. It should be fixed in a few hours.

**Comment by martinRenou** [comment]
@hbcarlos you may want to patch the package dependency in https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/main/recipe/gen_patch_json.py
