### ISSUE TITLE
Command to make cells draggable and resizable is incorrect

### ISSUE THREAD

**Issue by jpjon** [voila-dashboards/voila-gridstack#212]
### Problem
The given command from the `README.md` file here: 

`voila --template=gridstack examples/ --VoilaConfiguration.resources='{"gridstack": {"show_handles": True}}'`

is incorrect.

Examining voila arguments with `voila --help-all` helps clarify the correct format. Navigating to an example where `--VoilaConfiguration.resources` is used yield:

```
--VoilaConfiguration.resources=<key-1>=<value-1>...
    extra resources used by templates; example use with --template=reveal
    --VoilaConfiguration.resources="{'reveal': {'transition': 'fade', 'scroll':
    True}}"
```

### Suggested Improvement
The correct command should be:
`voila --template=gridstack examples/ --VoilaConfiguration.resources="{'gridstack': {'show_handles': True}}" `

**Comment by hbcarlos** [comment]
Fixed by #213
