### ISSUE TITLE
README documentation error

### ISSUE THREAD

**Issue by schorndorfer** [voila-dashboards/voila-gridstack#24]
I believe "False" should be "True":

By default the position of cells in the dashboard will be fixed. If you want them to be draggable and resizable, you can launch voila with the show_handles resource set to False:

voila --template=gridstack examples/ --VoilaConfiguration.resources='{"gridstack": {"show_handles": False}}

**Comment by SylvainCorlay** [comment]
Fixed in master! Thanks for reporting.

**Comment by schorndorfer** [comment]
Thanks for providing such great open source packages!
