### ISSUE TITLE
gridstack not working anymore?

### ISSUE THREAD

**Issue by schorndorfer** [voila-dashboards/voila-gridstack#27]
I have no idea why gridstack suddenly stopped working for me. For example, this is that scotch dashboard in mybinder looks like in my browser. Also, setting "show_handles" to True does show handles, but they are inert, you can't drag or re-size the cells they're attached to.

https://notebooks.gesis.org/binder/jupyter/user/voila-dashboards-voila-gridstack-71knqreb/voila/render/examples/scotch_dashboard.ipynb

<img width="1459" alt="Screen Shot 2019-11-17 at 9 37 13 PM" src="https://user-images.githubusercontent.com/781934/69022974-b5e05d80-0982-11ea-94ce-492d147e8a59.png">

**Comment by cnydw** [comment]
Apparently gridstack stopped providing their static js, css files from `https://gridstackjs.com/dist/gridstack.js` or `https://gridstackjs.com/dist/gridstack.css` anymore.

[js part](https://github.com/voila-dashboards/voila-gridstack/blob/69e0e7eb3797975f8301118d43f7fa49e1ec66b1/share/jupyter/voila/templates/gridstack/nbconvert_templates/grid.tpl#L9)
[css part](https://github.com/voila-dashboards/voila-gridstack/blob/b3f53e7f7de20a226ac931b26e933181979aafac/share/jupyter/voila/templates/gridstack/nbconvert_templates/gridstack_base.tpl#L18)

So we might want to serve the files from `https://www.jsdelivr.com` like https://gridstackjs.com/#getStarted, or directly from local dir, like mentioned in #26.

**Comment by schorndorfer** [comment]
I see, thanks for clearing that up.
