### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jtpio** [voila-dashboards/voila-gridstack#32]
How about releasing a new version of the template to include the CDN fix from #28?

Otherwise the template is not usable when pulling the latest version.

cc @SylvainCorlay

**Comment by SylvainCorlay** [comment]
@jtpio sounds good to me.

**Comment by jtpio** [comment]
Good.

I would be happy to do it but don't have the rights on PyPI: https://pypi.org/project/voila-gridstack/

**Comment by jtpio** [comment]
`0.0.8` was released a few days ago and is now available on both PyPI and conda forge.
