### ISSUE TITLE
gridstack template renders only one plot

### ISSUE THREAD

**Issue by Okroshiashvili** [voila-dashboards/voila-gridstack#35]
I encountered this issue today. I have a notebook with several **Plotly** plots. Running ```voila notebook.ipynb``` shows all the plots that I have but running ```voila notebook.ipynb --template=gridstack``` only shows the first plot. I tried ```voila --template=gridstack notebook.ipynb --VoilaConfiguration.resources='{"gridstack": {"show_handles": True}}'``` but got the same issue.

How can I solve this?

**Comment by jtpio** [comment]
Thanks @Okroshiashvili.

Would you be able to try with the latest releases of `voila` and `voila-gridstack`, to check if this is still an issue?

**Comment by Okroshiashvili** [comment]
@jtpio I updated ```voila``` and ```voila-gridstack``` but now only plot titles are showing, the plots itself are not rendered

**Comment by hbcarlos** [comment]
Hi everyone!
It looks like this issue is solved:

https://user-images.githubusercontent.com/26092748/143616626-b985809c-31ce-4875-81fb-689cf86229dd.mp4

I'm closing it, but feel free to reopen if the issue persists for you.
