### ISSUE TITLE
Update to gridstack 2.0.0

### ISSUE THREAD

**Issue by jtpio** [voila-dashboards/voila-gridstack#48]
`gridstack@v2.0.0` was just released: https://github.com/gridstack/gridstack.js/releases/tag/v2.0.0

We should look into the places where it is referenced and start updating to the new version.

- `v1.0.0` vendored here: 

https://github.com/voila-dashboards/voila-gridstack/blob/0c9ce7909b61bd86478c10b3ed25b590ae2b35a1/voila-gridstack/static/gridstack.js#L2

- `v0.5.2` referenced here:

https://github.com/voila-dashboards/voila-gridstack/blob/0c9ce7909b61bd86478c10b3ed25b590ae2b35a1/share/jupyter/nbconvert/templates/gridstack/gridstack_base.html.j2#L4

- JQuery UI Drag&Drop plugin `v1.0.0-dev` referenced here:

https://github.com/voila-dashboards/voila-gridstack/blob/0c9ce7909b61bd86478c10b3ed25b590ae2b35a1/voila-gridstack/static/gridstack.jqueryUI_require.js#L1

We could start using the same version everywhere to keep the same API across the code base.

**Comment by adumesny** [comment]
good thing I'm putting the actual rev number as preserved comments! you can tell what rev each use. See my comment on #26
