### ISSUE TITLE
[classic notebook editor] The classic layout editor un-hides hidden cells

### ISSUE THREAD

**Issue by SylvainCorlay** [voila-dashboards/voila-gridstack#63]
A simple way to reproduce this bug is by opening the example notebook in the layout editor, and saving the layout without any change.

**Comment by jtpio** [comment]
Yes, that and a couple of other styling issues after switching to 2.0.

1.0 (247ad1d0f589ec7920b37b7b093aa3c7b61a0c8c):

![image](https://user-images.githubusercontent.com/591645/93866697-4df85300-fcc8-11ea-8254-7874420ddf3f.png)

2.0 (ac0c7debddb4169a6ff3eca469d501ff8dc8caf0):

![image](https://user-images.githubusercontent.com/591645/93866781-6cf6e500-fcc8-11ea-9393-0df4c0eeab8a.png)
