### ISSUE TITLE
When opening a second editor focuses the first one

### ISSUE THREAD

**Issue by hbcarlos** [voila-dashboards/voila-gridstack#77]
When there is an editor open for one notebook and opening a second one for another notebook JupyterLab changes the focused widget of the main area to the first editor.

**Comment by fcollonval** [comment]
This is due to the hard coded id in the editor:

https://github.com/voila-dashboards/voila-gridstack/blob/bb717a15f46aea925cb7f58a87d1161a7bc48ba9/packages/jupyterlab-gridstack/src/editor/widget.ts#L35

**Comment by hbcarlos** [comment]
Thanks, Frédéric! Do you want to open a PR?
