### ISSUE TITLE
JupyterLab 3 on Binder

### ISSUE THREAD

**Issue by hbcarlos** [voila-dashboards/voila-gridstack#79]
Binder is using Jupyter la 2.2 even trying to force it to use Lab 3 on the config file.
https://github.com/voila-dashboards/voila-gridstack/blob/71c5a5bd2f0b9b2e8a180d5f67098c856da4631f/binder/environment.yml#L11

**Comment by jtpio** [comment]
Probably because the link points to the `stable` branch.

I'll reset the `stable` branch onto the latest to pick the new changes.

**Comment by jtpio** [comment]
For now it can be tested with: 

https://mybinder.org/v2/gh/voila-dashboards/voila-gridstack/master?urlpath=lab/tree/examples

**Comment by hbcarlos** [comment]
Awesome! Works perfectly!

**Comment by jtpio** [comment]
Should be good now with the stable link:

https://mybinder.org/v2/gh/voila-dashboards/voila-gridstack/stable?urlpath=lab/tree/examples

**Comment by jtpio** [comment]
We might want to add a couple more dependencies for the iris example to work though.

**Comment by hbcarlos** [comment]
Yep, I'll add them

**Comment by jtpio** [comment]
Closing as fixed.
