### ISSUE TITLE
[DISCUSS] Grid Layout Persistence

### ISSUE THREAD

**Issue by echarles** [voila-dashboards/voila-gridstack#8]
Hi, Grid layout changes are lost on page refresh or voila server restart. Will Voila provide a way to persist the layout and what is the plan for this? Is it reasonable to add metadata to the notebook file for this?

**Comment by SylvainCorlay** [comment]
Absoluty. Therenis a spec for such metadata in the now deprecated "jupyter-dashboard" project that is based on gridstack as well.

Do you feel like taking a stab at it?

**Comment by echarles** [comment]
@SylvainCorlay I will get inspiration from deprecated `jupyter-dashboard` and take a few cycles next week to implement this.

**Comment by SylvainCorlay** [comment]
Thanks @echarles! That is awesome. I am off on Monday but would be happy to connect with you if you have any question latee in the week.

**Comment by icfly2** [comment]
Hey any progress on this? are there ideas as to how to hack this?

**Comment by SylvainCorlay** [comment]
Hey @echarles, we just merged the support of the jupyter-dashboards layout in master!

The next step w.r.t. implementation is the WYSIWYG editor in jupyterlab.

I am closing this issue as outdated, but we would appreciate your help for improving voila-gridstack and the implementation of the layout editor.

**Comment by SylvainCorlay** [comment]
Closing this issue as outdated.

**Comment by echarles** [comment]
Hi Sylvain, does it mean that the layout persistence is supported/implemented with jupyter-dashboards? Is seems like [it is](tps://jupyter-dashboards-layout.readthedocs.io/en/latest/using.html) but happy to learn more on this (I don't know the jupyter-dashboard features).

**Comment by SylvainCorlay** [comment]
jupyter-dashboards included a WYSIWYG layout editor for the classic notebook environment. (See screenshot below)

![editor](https://user-images.githubusercontent.com/2397974/68544649-3f3bd280-037a-11ea-88aa-1c0e798377a4.png)

 It produced a layout spec which is the one that voila-gridstack is now consuming. The plan is now to implement a similar layout editor as a JupyterLab extension as part of voilà-gridstack. Although the work that we are doing with gridstack is not funded work, and any help will be super welcome.

**Comment by damianavila** [comment]
I was going to ask for the editor, it is nice to know it is on the roadmap!

**Comment by brichet** [comment]
Hi,
Is there some progress on that feature ?
Is that still in the roadmap ?

**Comment by StefanBrand** [comment]
> Hey @echarles, we just merged the support of the jupyter-dashboards layout in master!

For reference: f46c5bc5e945b26843600365c0759d5b76194fc2

**Comment by StefanBrand** [comment]
It's actually possible to persist the grid by manipulating the metadata of cells. You can get the required parameters from the interactive grid with handles:

![voila-gridstack with handles](https://user-images.githubusercontent.com/8948865/114855254-095c1280-9de6-11eb-8456-5fea8589a512.png)

In the _Advanced Tools_ section of the _Property Inspector_ you can add parameters like this:

![cell metadata - advanced tools - property inspector -jupyter lab](https://user-images.githubusercontent.com/8948865/114855373-301a4900-9de6-11eb-9d58-2dd04cc33291.png)

I took inspiration from the tests:

https://github.com/voila-dashboards/voila-gridstack/blob/f46c5bc5e945b26843600365c0759d5b76194fc2/tests/nb.ipynb#L7-L23

https://github.com/voila-dashboards/voila-gridstack/blob/f46c5bc5e945b26843600365c0759d5b76194fc2/tests/nb.ipynb#L41-L53
