### ISSUE TITLE
voila-gridstack

### ISSUE THREAD

**Issue by aganjidoost** [voila-dashboards/voila-gridstack#85]
I use jupyter/voila with Plotly, but when I launch voila-gridstack, I see the attached output at the bottom of the voila dashboard (I didn't have this issue before). Your help/advice to resolve this issue is greatly appreciated.
![Voila](https://user-images.githubusercontent.com/43971531/110823201-da3f0800-825f-11eb-92fa-544ef5342c9e.png)

Thanks. Amin.

**Comment by jtpio** [comment]
Thanks @aganjidoost for reporting.

It looks similar to this issue in Voila: https://github.com/voila-dashboards/voila/issues/491

Although not sure there has been any fix for it yet.

Which versions of `voila` and `voila-gridstack` are you using?

**Comment by aganjidoost** [comment]
Thanks for your replay @jtpio 
I use voila 0.2.7 and  voila-gridstack 0.2.7

**Comment by aganjidoost** [comment]
@jtpio, any solution for this issue?

**Comment by jtpio** [comment]
@aganjidoost would it be possible to share a minimal example of the notebook you are using, to reproduce the issue?

**Comment by hbcarlos** [comment]
Hi everyone!
I'm looking around trying to close issues. I tried the latest voila-gridstack with plotly and looks like it works as expected.

https://user-images.githubusercontent.com/26092748/143616626-b985809c-31ce-4875-81fb-689cf86229dd.mp4

Closing the issue. Feel free to reopen if the issue persists for you.
