### ISSUE TITLE
Output is different on Firefox and Chrome

### ISSUE THREAD

**Issue by echarles** [voila-dashboards/voila-gridstack#9]
There are 2 additional paragraphs shown on Chrome (not present on Firefox).

<img width="1211" alt="Chrome" src="https://user-images.githubusercontent.com/226720/61168684-1d5c4b80-a552-11e9-9970-99bb96ee54ab.png">
<img width="1184" alt="Firefox" src="https://user-images.githubusercontent.com/226720/61168685-1d5c4b80-a552-11e9-83c0-33f2e8b36229.png">

**Comment by jtpio** [comment]
Testing locally with voila `0.1.13`, I get the same outputs / boxes but in a different order with Firefox and Chrome.

@echarles do you get the same behavior with `0.1.13`?

**Comment by echarles** [comment]
@jtpio Just tested with latest voila master, and I have now the same behavior as you: the 2 first boxes displayed in Chrome are displayed at the end in Firefox.

I had a quick look at the create DOM in both cases, and indeed the DOM shows the divs with class `grid-stack-item ui-draggable ui-resizable ui-resizable-autohide` in different order. The next step would be to inspect the js/server communication.

**Comment by SylvainCorlay** [comment]
@echarles we are now using the layout spec from `jupyter-dashboards` and this issue corresponds to the previous behavior of voilà-gridstack. I am closing this issue as outdated.
