### ISSUE TITLE
Use a closer approach to clone output view

### ISSUE THREAD

**Issue by fcollonval** [voila-dashboards/voila-gridstack#92]
Hey 

This is more a question than a bug per se. I was wondering if it makes sense to move to a sibling pattern like the one use for the cloned output view rather than the factory:

https://github.com/jupyterlab/jupyterlab/blob/82604b43eb5563b0cee5fc69fcf4ee52ef46b15c/packages/notebook-extension/src/index.ts#L645

**Comment by jtpio** [comment]
Thanks @fcollonval for opening this.

I think the sibling pattern was indeed considered as a way to simplify things.

However it looks like the sibling would be disposed when the main widget is disposed:

https://github.com/jupyterlab/jupyterlab/blob/82604b43eb5563b0cee5fc69fcf4ee52ef46b15c/packages/notebook-extension/src/index.ts#L660-L665

And currently it's possible to open the voila gridstack editor alone (as a document widget) without the source notebook to be open:

![image](https://user-images.githubusercontent.com/591645/112114687-a2698600-8bb8-11eb-9053-bfd7c349e6cc.png)

**Comment by fcollonval** [comment]
Indeed the factory approach as the interesting feature to open notebook with gridstack editor alone.

Thanks for sharing your thoughts on this.
